http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
        
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - "/api"
  
  services:
    forms-data-handler-service:
      loadBalancer:
        servers:
          - url: "http://forms-data-handler:3000"